-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 18:10:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`zamestnavatelia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zamestnavatelia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazov_firmy` VARCHAR(45) NOT NULL,
  `kontakt_meno` VARCHAR(30) NULL,
  `kontakt_priezvisko` VARCHAR(45) NULL,
  `kontakt_telefon` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brigady_kategorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brigady_kategorie` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(45) NOT NULL,
  `popis` MEDIUMTEXT NULL,
  `hodinova_sadzba` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brigady`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brigady` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(45) NOT NULL,
  `zamestnavatelia_id` INT NOT NULL,
  `brigady_kategorie_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_brigady_zamestnavatelia1_idx` (`zamestnavatelia_id` ASC) VISIBLE,
  INDEX `fk_brigady_brigady_kategorie1_idx` (`brigady_kategorie_id` ASC) VISIBLE,
  CONSTRAINT `fk_brigady_zamestnavatelia1`
    FOREIGN KEY (`zamestnavatelia_id`)
    REFERENCES `mydb`.`zamestnavatelia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brigady_brigady_kategorie1`
    FOREIGN KEY (`brigady_kategorie_id`)
    REFERENCES `mydb`.`brigady_kategorie` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`zrucnosti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`zrucnosti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nazov` VARCHAR(45) NOT NULL,
  `popis` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studenti` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `meno` VARCHAR(30) NOT NULL,
  `priezvisko` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(15) NULL,
  `zarobok` FLOAT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`studenti_has_zrucnosti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`studenti_has_zrucnosti` (
  `studenti_id` INT NOT NULL,
  `zrucnosti_id` INT NOT NULL,
  PRIMARY KEY (`studenti_id`, `zrucnosti_id`),
  INDEX `fk_studenti_has_zrucnosti_zrucnosti1_idx` (`zrucnosti_id` ASC) VISIBLE,
  INDEX `fk_studenti_has_zrucnosti_studenti1_idx` (`studenti_id` ASC) VISIBLE,
  CONSTRAINT `fk_studenti_has_zrucnosti_studenti1`
    FOREIGN KEY (`studenti_id`)
    REFERENCES `mydb`.`studenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_studenti_has_zrucnosti_zrucnosti1`
    FOREIGN KEY (`zrucnosti_id`)
    REFERENCES `mydb`.`zrucnosti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brigady_require_zrucnosti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brigady_require_zrucnosti` (
  `brigady_id` INT NOT NULL,
  `zrucnosti_id` INT NOT NULL,
  PRIMARY KEY (`brigady_id`, `zrucnosti_id`),
  INDEX `fk_brigady_has_zrucnosti_zrucnosti1_idx` (`zrucnosti_id` ASC) VISIBLE,
  INDEX `fk_brigady_has_zrucnosti_brigady1_idx` (`brigady_id` ASC) VISIBLE,
  CONSTRAINT `fk_brigady_has_zrucnosti_brigady1`
    FOREIGN KEY (`brigady_id`)
    REFERENCES `mydb`.`brigady` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brigady_has_zrucnosti_zrucnosti1`
    FOREIGN KEY (`zrucnosti_id`)
    REFERENCES `mydb`.`zrucnosti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`brigady_has_studenti`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`brigady_has_studenti` (
  `brigady_id` INT NOT NULL,
  `studenti_id` INT NOT NULL,
  `mzda` FLOAT NOT NULL,
  `datum_od` DATE NOT NULL,
  `datum_do` DATE NULL,
  `provizia_agentury` FLOAT NULL,
  PRIMARY KEY (`brigady_id`, `studenti_id`),
  INDEX `fk_brigady_has_studenti_studenti1_idx` (`studenti_id` ASC) VISIBLE,
  INDEX `fk_brigady_has_studenti_brigady1_idx` (`brigady_id` ASC) VISIBLE,
  CONSTRAINT `fk_brigady_has_studenti_brigady1`
    FOREIGN KEY (`brigady_id`)
    REFERENCES `mydb`.`brigady` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_brigady_has_studenti_studenti1`
    FOREIGN KEY (`studenti_id`)
    REFERENCES `mydb`.`studenti` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
